workflows:
  ios:
    name: iOS Build
    instance_type: mac_mini
    environment:
      ios_signing:
        distribution_type: ad_hoc
      vars:
        BUNDLE_ID: com.medidormetro.app
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - dfgarcia2908@gmail.com
